apiVersion: v1
kind: ConfigMap
metadata:
  name: stellarsync-config
  namespace: stellarsync
data:
  DOMAIN: 'stellar.kasu.network'
  EMAIL: 'your-email@example.com'
  DOCKER_IMAGE_MAIN: 'kasuaberra/stellarsync-main:latest'
  DOCKER_IMAGE_FILESERVER: 'kasuaberra/stellarsync-fileserver:latest'


